(() => {
  const api = window.lingframe;
  if (!api?.generation) return;
  let providers = [];
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const accounts = () => window.lingframeAccountStore?.accounts?.() || [];
  function toast(message, error = false) { let node = document.querySelector('.pm-toast'); if (!node) { node = document.createElement('div'); document.body.appendChild(node); } node.className = `pm-toast ${error ? 'error' : ''}`; node.textContent = message; clearTimeout(node.timer); node.timer = setTimeout(() => node.remove(), 3500); }
  function confirmModelCancel() {
    return new Promise(resolve => {
      const host = document.createElement('div');
      host.className = 'pm-modal';
      host.innerHTML = `<div class="pm-modal-backdrop" data-model-cancel-close></div><div class="pm-dialog glass"><div class="pm-dialog-head"><div><b>取消模型任务</b><span>如果厂商不支持远程取消，只会停止本地追踪，厂商仍可能继续执行和计费。</span></div><button data-model-cancel-close>×</button></div><div class="pm-dialog-actions"><button class="ghost" data-model-cancel-close>返回</button><button class="primary danger-confirm" data-model-cancel-confirm>确认取消</button></div></div>`;
      document.body.appendChild(host);
      const done = value => { host.remove(); resolve(value); };
      host.querySelectorAll('[data-model-cancel-close]').forEach(node => { node.onclick = () => done(false); });
      host.querySelector('[data-model-cancel-confirm]').onclick = () => done(true);
    });
  }
  function addFields(modal) {
    if (!modal || modal.querySelector('[data-generation-channel]')) return;
    const anchor = modal.querySelector('[data-task-prompt]')?.closest('label'); if (!anchor) return;
    const box = document.createElement('div'); box.className = 'generation-fields';
    box.innerHTML = `<label>执行通道<select data-generation-channel><option value="doubao">豆包账号</option><option value="model-gateway">模型网关</option></select></label><label data-generation-account>豆包账号<select data-generation-account-select>${accounts().map(item => `<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('')}</select></label><label data-generation-doubao-model>豆包模型<select data-generation-doubao-model-select><option value="Seedance 2.0 Fast">Seedance 2.0 Fast</option><option value="Seedance 2.0 Mini" selected>Seedance 2.0 Mini</option></select></label><label data-generation-ratio>画面比例<select data-generation-ratio-select>${['自动','3:4','4:3','9:16','16:9','1:1','21:9'].map(value=>`<option value="${value}">${value}</option>`).join('')}</select></label><label data-generation-duration>视频时长<select data-generation-duration-select>${Array.from({length:12},(_,index)=>index+4).map(value=>`<option value="${value}s" ${value===10?'selected':''}>${value} 秒</option>`).join('')}</select></label><label data-generation-model style="display:none">模型<select data-generation-model-select>${providers.flatMap(provider => (provider.models || []).filter(model => model.enabled !== false).map(model => `<option value="${esc(provider.id)}::${esc(model.id)}">${esc(provider.name)} / ${esc(model.displayName)}</option>`)).join('') || '<option value="">请先在系统设置添加模型</option>'}</select></label>`;
    anchor.insertAdjacentElement('afterend', box);
    const channel = box.querySelector('[data-generation-channel]'); const account = box.querySelector('[data-generation-account]'); const model = box.querySelector('[data-generation-model]');
    channel.onchange = () => { const gateway = channel.value === 'model-gateway'; account.style.display = gateway ? 'none' : ''; model.style.display = gateway ? '' : 'none';for(const selector of ['[data-generation-doubao-model]','[data-generation-ratio]','[data-generation-duration]'])box.querySelector(selector).style.display=gateway?'none':''; };
  }
  async function loadProviders() { try { providers = await (api.models?.executionCatalog?.() || api.models?.bootstrap?.()) || []; } catch { providers = []; } }
  async function submitTask(button) {
    const modal = button.closest('.pm-modal'); if (!modal) return;
    const title = modal.querySelector('[data-task-title]')?.value.trim(); const prompt = modal.querySelector('[data-task-prompt]')?.value.trim(); const projectId = modal.querySelector('[data-task-project]')?.value;
    if (!title || !prompt) return toast('请填写任务名称和提示词', true);
    const channel = modal.querySelector('[data-generation-channel]')?.value || 'doubao'; const input = {title, prompt, projectId, creationType:'video', executionChannel:channel};
    if (channel === 'doubao') { const account = modal.querySelector('[data-generation-account-select]'); const item = accounts().find(x => x.id === account?.value) || accounts()[0]; input.accountId = item?.id || ''; input.accountName = item?.name || '';input.doubaoModel=modal.querySelector('[data-generation-doubao-model-select]')?.value||'Seedance 2.0 Mini';input.ratio=modal.querySelector('[data-generation-ratio-select]')?.value||'自动';input.duration=modal.querySelector('[data-generation-duration-select]')?.value||'10s'; }
    else { const selected = modal.querySelector('[data-generation-model-select]')?.value || ''; const [providerId, ...modelParts] = selected.split('::'); input.providerId = providerId; input.modelId = modelParts.join('::'); }
    button.disabled = true;
    try { const task = await api.generation.create(input); modal.remove(); toast(`任务已提交：${task.title}`); document.querySelector('[data-task-refresh]')?.click(); }
    catch (error) { toast(String(error.message || error), true); button.disabled = false; }
  }
  document.addEventListener('click', event => { const button = event.target.closest('[data-task-create-save]'); if (!button) return; event.preventDefault(); event.stopImmediatePropagation(); submitTask(button); }, true);
  document.addEventListener('click', async event => {
    const taskIdFor = button => button?.dataset.taskId || button?.closest('#generation-live-shell')?.dataset.liveTaskId || document.querySelector('.task-card.on,[data-task-select].on')?.dataset.taskSelect || '';
    const openScene = event.target.closest('[data-task-open-scene]');
    if (openScene) { event.preventDefault(); event.stopImmediatePropagation(); const accountId=openScene.dataset.accountId||activeTask()?.accountId||''; if(!accountId)return toast('未找到原豆包账号',true); openScene.disabled=true; Promise.resolve(api.doubao?.activateAccount?.(accountId)).then(()=>{toast('已打开原账号窗口，请在原会话核对')}).catch(error=>toast(String(error.message||error),true)).finally(()=>{openScene.disabled=false}); return; }
    const resume = event.target.closest('[data-task-resume]');
    if (resume) { event.preventDefault(); event.stopImmediatePropagation(); const taskId=taskIdFor(resume); if (!taskId) return toast('未找到当前任务', true); resume.disabled = true; api.generation.resume(taskId).then(() => { toast('已继续原账号和原会话，不会重新提交'); document.querySelector('[data-task-refresh]')?.click(); }).catch(error => { toast(String(error.message || error), true); resume.disabled = false; }); return; }
    const monitorUnknown=event.target.closest('[data-task-monitor-unknown]');
    if(monitorUnknown){event.preventDefault();event.stopImmediatePropagation();const taskId=taskIdFor(monitorUnknown);if(!taskId)return toast('未找到当前任务',true);monitorUnknown.disabled=true;api.generation.resolveSubmissionUnknown(taskId,'submitted').then(()=>{toast('当前会话与提示词匹配成功，已继续监控');document.querySelector('[data-task-refresh]')?.click()}).catch(error=>{toast(String(error.message||error),true);monitorUnknown.disabled=false});return;}
    const resolveFailed=event.target.closest('[data-task-resolve-failed]');
    if(resolveFailed){event.preventDefault();event.stopImmediatePropagation();const taskId=taskIdFor(resolveFailed);if(!taskId)return toast('未找到当前任务',true);const host=document.createElement('div');host.className='pm-modal';host.innerHTML=`<div class="pm-modal-backdrop" data-failed-close></div><div class="pm-dialog glass"><div class="pm-dialog-head"><div><b>确认豆包已经生成失败？</b><span>仅在原豆包会话已经明确显示失败、停止或无法生成时使用。</span></div><button data-failed-close>×</button></div><div class="task-error"><b>确认后将结束当前任务</b><p>系统会停止自动监控、释放账号并保留人工核对证据，不会自动重新提交。</p><span>之后可以修改提示词、素材或参数，创建新的子任务重试。</span></div><div class="pm-dialog-actions"><button class="ghost" data-failed-close>继续保持保护</button><button class="primary danger-confirm" data-failed-confirm>确认豆包已失败</button></div></div>`;document.body.appendChild(host);host.querySelectorAll('[data-failed-close]').forEach(node=>node.onclick=()=>host.remove());host.querySelector('[data-failed-confirm]').onclick=async()=>{const button=host.querySelector('[data-failed-confirm]');button.disabled=true;try{await api.generation.resolveSubmissionUnknown(taskId,'failed');host.remove();toast('已确认失败并释放账号；系统没有自动重提');document.querySelector('[data-task-refresh]')?.click()}catch(error){toast(String(error.message||error),true);button.disabled=false}};return;}
    const resolveNotSubmitted=event.target.closest('[data-task-resolve-not-submitted]');
    if(resolveNotSubmitted){event.preventDefault();event.stopImmediatePropagation();const taskId=taskIdFor(resolveNotSubmitted);if(!taskId)return toast('未找到当前任务',true);const host=document.createElement('div');host.className='pm-modal';host.innerHTML=`<div class="pm-modal-backdrop" data-unknown-close></div><div class="pm-dialog glass"><div class="pm-dialog-head"><div><b>确认原会话没有本次提交？</b><span>仅在你已打开原账号、核对原 conversation，并确认没有本次提示词或生成任务时使用。</span></div><button data-unknown-close>×</button></div><div class="task-error"><b>这是人工解除保护操作</b><p>确认后会结束当前“提交状态未知”保护并释放账号，但不会自动重新提交。若豆包实际上已经收到任务，可能出现遗漏监控。</p><span>系统会保留人工核对时间、账号和 conversation 证据。</span></div><div class="pm-dialog-actions"><button class="ghost" data-unknown-close>继续保持保护</button><button class="primary danger-confirm" data-unknown-confirm>确认未提交，结束保护</button></div></div>`;document.body.appendChild(host);host.querySelectorAll('[data-unknown-close]').forEach(node=>node.onclick=()=>host.remove());host.querySelector('[data-unknown-confirm]').onclick=async()=>{const button=host.querySelector('[data-unknown-confirm]');button.disabled=true;try{await api.generation.resolveSubmissionUnknown(taskId,'not_submitted');host.remove();toast('已结束保护并释放账号；系统没有自动重提');document.querySelector('[data-task-refresh]')?.click()}catch(error){toast(String(error.message||error),true);button.disabled=false}};return;}
    const doubaoResultAction=event.target.closest('[data-doubao-result-retry],[data-doubao-result-cancel]');
    if(doubaoResultAction){event.preventDefault();event.stopImmediatePropagation();const taskId=taskIdFor(doubaoResultAction);if(!taskId)return toast('未找到当前豆包任务',true);if(doubaoResultAction.matches('[data-doubao-result-cancel]')&&!window.confirm('只取消本地素材回传，豆包中已经生成的视频不会被删除。确定继续吗？'))return;doubaoResultAction.disabled=true;const operation=doubaoResultAction.matches('[data-doubao-result-retry]')?api.generation.retryDoubaoResult(taskId):api.generation.cancel(taskId);Promise.resolve(operation).then(()=>toast(doubaoResultAction.matches('[data-doubao-result-retry]')?'正在重新回传已有豆包视频，不会重新生成':'已取消本地素材回传')).catch(error=>{toast(String(error.message||error),true);doubaoResultAction.disabled=false});return;}
    const modelAction=event.target.closest('[data-live-model-edit],[data-live-model-pause],[data-live-model-resume],[data-live-model-retry],[data-live-model-cancel]');
    if(modelAction){event.preventDefault();event.stopImmediatePropagation();const taskId=taskIdFor(modelAction),item=activeTask();if(!taskId||!item)return toast('未找到当前模型任务',true);if(modelAction.matches('[data-live-model-edit]')){const urls=[...new Set([...(item.resultItems||[]).map(value=>value.url),...(item.resultUrls||[])].filter(Boolean))],host=document.createElement('div');host.className='pm-modal';host.innerHTML=`<div class="pm-modal-backdrop" data-model-close></div><div class="pm-dialog glass"><div class="pm-dialog-head"><div><b>修改模型结果</b><span>每行一个结果地址；只恢复下载和入库，不会重新生成。</span></div><button data-model-close>×</button></div><label>结果类型<select data-model-type>${['image','video','audio'].map(value=>`<option value="${value}" ${value===(item.resultType||item.creationType)?'selected':''}>${value}</option>`).join('')}</select></label><label>结果地址<textarea rows="8" data-model-urls>${esc(urls.join('\n'))}</textarea></label><label>预期结果数<input type="number" min="1" max="20" data-model-count value="${Math.max(1,Number(item.expectedResultCount||urls.length||1))}"></label><div class="pm-dialog-actions"><button class="ghost" data-model-close>取消</button><button class="primary" data-model-save>保存并恢复</button></div></div>`;document.body.appendChild(host);host.querySelectorAll('[data-model-close]').forEach(node=>node.onclick=()=>host.remove());host.querySelector('[data-model-save]').onclick=async()=>{const button=host.querySelector('[data-model-save]'),resultUrls=host.querySelector('[data-model-urls]').value.split(/\r?\n/).map(value=>value.trim()).filter(Boolean);if(!resultUrls.length)return toast('请填写结果地址',true);button.disabled=true;try{await api.generation.updateModelResult(taskId,{resultUrls,resultType:host.querySelector('[data-model-type]').value,expectedResultCount:Number(host.querySelector('[data-model-count]').value)||resultUrls.length,replace:true});host.remove();toast('已更新结果地址并恢复回传')}catch(error){toast(String(error.message||error),true);button.disabled=false}};return;}if(modelAction.matches('[data-live-model-cancel]')&&!(await confirmModelCancel()))return;modelAction.disabled=true;const operation=modelAction.matches('[data-live-model-pause]')?api.generation.pauseModel(taskId):modelAction.matches('[data-live-model-resume]')?api.generation.resumeModel(taskId):modelAction.matches('[data-live-model-retry]')?api.generation.retryModelResult(taskId):api.generation.cancel(taskId);Promise.resolve(operation).then(()=>toast(modelAction.matches('[data-live-model-cancel]')?'已停止模型任务追踪':'模型任务状态已更新')).catch(error=>{toast(String(error.message||error),true);modelAction.disabled=false});return;}
    const button = event.target.closest('[data-text-generate]'); if (!button || window.lingframeTextAiBatchC?.ownsTextGeneration) return;
    event.preventDefault(); event.stopImmediatePropagation();
    const content = document.querySelector('[data-text-content]')?.value.trim(); if (!content) return toast('请先输入文本创作内容', true);
    const editor = document.querySelector('.text-editor'); const host = document.createElement('div'); host.className = 'pm-modal';
    host.innerHTML = `<div class="pm-modal-backdrop" data-generation-close></div><div class="pm-dialog glass"><div class="pm-dialog-head"><div><b>选择文本执行通道</b><span>生成结果会保存到当前创作和任务中心。</span></div><button data-generation-close>×</button></div><label>执行通道<select data-text-channel><option value="model-gateway">模型网关</option><option value="doubao">豆包账号</option></select></label><label data-text-account style="display:none">豆包账号<select data-text-account-select>${accounts().map(item => `<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('')}</select></label><label data-text-model>模型<select data-text-model-select>${providers.flatMap(provider => (provider.models || []).filter(model => model.capabilities?.type === 'text' && model.enabled !== false).map(model => `<option value="${esc(provider.id)}::${esc(model.id)}">${esc(provider.name)} / ${esc(model.displayName)}</option>`)).join('') || '<option value="">请先配置文本模型</option>'}</select></label><div class="pm-dialog-actions"><button class="ghost" data-generation-close>取消</button><button class="primary" data-text-generation-submit>开始生成</button></div></div>`;
    document.body.appendChild(host); host.querySelectorAll('[data-generation-close]').forEach(node => node.onclick = () => host.remove());
    const channel = host.querySelector('[data-text-channel]'); channel.onchange = () => { const gateway = channel.value === 'model-gateway'; host.querySelector('[data-text-account]').style.display = gateway ? 'none' : ''; host.querySelector('[data-text-model]').style.display = gateway ? '' : 'none'; };
    host.querySelector('[data-text-generation-submit]').onclick = async () => { const input = {title: document.querySelector('[data-text-title]')?.value || '文本创作', prompt: content, projectId: editor?.dataset.textProjectId, conversationId: editor?.dataset.textConversationId, creationType:'text', executionChannel:channel.value}; if (channel.value === 'doubao') { const item = accounts().find(x => x.id === host.querySelector('[data-text-account-select]').value) || accounts()[0]; input.accountId = item?.id; input.accountName = item?.name; } else { const [providerId,...parts] = host.querySelector('[data-text-model-select]').value.split('::'); input.providerId = providerId; input.modelId = parts.join('::'); } try { await api.generation.create(input); host.remove(); toast('文本任务已提交到任务中心'); } catch (error) { toast(String(error.message || error), true); } };
  }, true);
  new MutationObserver(() => { const modal = document.querySelector('.pm-modal'); if (modal && modal.querySelector('[data-task-title]')) addFields(modal); }).observe(document.body, {childList:true, subtree:true});
  new MutationObserver(() => { const card = document.querySelector('.human-action-card:not(.unknown-review)'); if (card && !card.querySelector('[data-task-resume]')) card.insertAdjacentHTML('beforeend','<button class="primary" data-task-resume style="margin-top:10px">我已完成验证，继续原任务</button>'); }).observe(document.body,{childList:true,subtree:true});

  const liveTasks = new Map();
  const MAX_VISIBLE_LIVE_ROWS = 4;
  const terminalStates = new Set(['completed','failed','cancelled']);
  const indeterminateStates = new Set(['generating','submission_unknown']);
  // 终态失败不属于“实时任务”或“需处理”。失败任务统一保留在任务中心，
  // 只有仍有可恢复结果回传的任务才允许在任务坞里显示操作入口。
  const attentionStates = new Set(['awaiting_verification','awaiting_login','submission_unknown','paused']);
  const runningStates = new Set(['preparing','checking_login','uploading_references','uploading','configuring','submitting','generating','monitoring','result_detected','downloading','verifying']);
  const stageLabels={queued:'等待执行',preparing:'准备任务',checking_login:'检查登录',uploading_references:'上传参考图',uploading:'上传素材',configuring:'配置参数',submitting:'提交豆包',generating:'生成中',monitoring:'安全监控',result_detected:'捕获结果',downloading:'下载回传',verifying:'保存素材',awaiting_verification:'等待人工验证',awaiting_login:'等待重新登录',awaiting_quota:'等待额度恢复',submission_unknown:'等待人工核对',paused:'等待人工处理',completed:'已完成',failed:'执行失败',cancelled:'已取消'};
  let activeLiveTaskId = '';
  const activeTask = () => liveTasks.get(activeLiveTaskId);
  const canOpenWindow = item => Boolean(item?.executionChannel === 'doubao' && item.accountId);
  function isRecoverableFailure(item) { return item?.state==='failed' && item?.executionChannel==='doubao' && (item.resultUrls||[]).length > 0 && (item.retryMode==='recover_result'||['result_download_failed','result_review_required','validating_result','manual_retry'].includes(item.recoveryState)); }
  function needsLiveAttention(item) { return attentionStates.has(item?.state)||isRecoverableFailure(item); }
  function isLiveDockTask(item) { if(!item||item.deletedAt||item.archivedAt)return false; if(isRecoverableFailure(item))return true; return runningStates.has(item.state)||item.state==='queued'||item.state==='awaiting_quota'||attentionStates.has(item.state); }
  function attentionRank(item) { const state=item?.state;return ['awaiting_verification','awaiting_login','submission_unknown','paused'].includes(state)?0:isRecoverableFailure(item)?1:runningStates.has(state)?2:state==='queued'||state==='awaiting_quota'?3:5; }
  function sortedLiveTasks() { return [...liveTasks.values()].filter(isLiveDockTask).sort((a,b)=>attentionRank(a)-attentionRank(b)||Date.parse(b.updatedAt||b.receivedAt||0)-Date.parse(a.updatedAt||a.receivedAt||0)); }
  function trimLiveTasks() {
    const now=Date.now();
    for(const [id,item] of liveTasks){if(!isLiveDockTask(item)||(id!==activeLiveTaskId&&['completed','cancelled'].includes(item.state)&&now-Number(item.terminalAt||now)>60000))liveTasks.delete(id);}
    if(liveTasks.size<=24)return;
    for(const item of sortedLiveTasks().reverse()){if(item.taskId!==activeLiveTaskId&&!needsLiveAttention(item))liveTasks.delete(item.taskId);if(liveTasks.size<=24)break;}
  }
  function elapsedLabel(value) { const started=Date.parse(value?.createdAt||value?.receivedAt||value?.updatedAt||'');if(!Number.isFinite(started))return'';const seconds=Math.max(0,Math.floor((Date.now()-started)/1000));if(seconds<60)return`${seconds}秒`;const minutes=Math.floor(seconds/60);return minutes<60?`${minutes}分${seconds%60}秒`:`${Math.floor(minutes/60)}小时${minutes%60}分`; }
  function checkedLabel(value) { const time=Date.parse(value||'');return Number.isFinite(time)?new Date(time).toLocaleTimeString('zh-CN',{hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'}):''; }
  function stageLabel(item) { if(item?.state==='submission_unknown'&&item.executionChannel==='model-gateway')return(item.providerJobId||item.clientRequestId)&&!['query_unsupported','query_identifier_missing'].includes(item.recoveryState)?'接口核对中':'厂商状态待确认';return stageLabels[item?.stage||item?.state]||item?.stage||item?.state||'执行中'; }
  function modelUnknownNotice(item) { if((item.providerJobId||item.clientRequestId)&&!['query_unsupported','query_identifier_missing'].includes(item.recoveryState))return'模型网关请求返回超时，系统正在通过厂商任务接口自动核对；不会重新提交生成请求。';if(item.recoveryState==='query_unsupported')return'当前厂商未配置可用的任务查询接口；系统不会自动重发，请核对厂商任务记录。';return'该历史任务缺少可查询的厂商任务标识；系统不会自动重发，请核对厂商任务记录。'; }
  function isIndeterminate(item) { return item?.progressMode==='indeterminate'||indeterminateStates.has(item?.state); }
  function summaryCounts(){const values=[...liveTasks.values()].filter(isLiveDockTask);return{running:values.filter(item=>runningStates.has(item.state)).length,queued:values.filter(item=>item.state==='queued'||item.state==='awaiting_quota').length,attention:values.filter(needsLiveAttention).length,total:values.length};}
  function updateCollapseLabel(shell){const button=shell?.querySelector('#generation-live-collapse');if(!button)return;const counts=summaryCounts();button.textContent=shell.classList.contains('rail-unavailable')?(counts.attention?`需处理 ${counts.attention}`:`任务 ${counts.total}`):shell.classList.contains('collapsed')?`展开${counts.total?` ${counts.total}`:''}`:'收起';shell.classList.toggle('has-attention',counts.attention>0);}
  function syncLiveRailLayout(shell=document.querySelector('#generation-live-shell')) {
    if(!shell)return;const rail=document.querySelector('.shell:not(.right-off):not([data-current-page="canvas"]) .right');const rect=rail?.getBoundingClientRect();const status=document.querySelector('.statusbar')?.getBoundingClientRect();
    if(rect&&rect.width>120&&rect.height>120){const inset=8;shell.classList.remove('rail-unavailable');shell.style.left=`${Math.round(rect.left+inset)}px`;shell.style.top=`${Math.round(rect.top+inset)}px`;shell.style.height=`${Math.max(120,Math.round(rect.height-inset*2))}px`;shell.style.maxHeight=`${Math.max(120,Math.round(rect.height-inset*2))}px`;shell.style.removeProperty('min-width');shell.style.removeProperty('max-width');shell.style.width=`${Math.max(208,Math.round(rect.width-inset*2))}px`;shell.style.right='auto';shell.style.bottom='auto';}
    else{shell.classList.add('rail-unavailable','collapsed');shell.style.removeProperty('top');shell.style.removeProperty('height');shell.style.removeProperty('max-height');shell.style.left=`${Math.max(8,window.innerWidth-158)}px`;shell.style.setProperty('width','148px','important');shell.style.setProperty('min-width','148px','important');shell.style.setProperty('max-width','148px','important');shell.style.right='auto';shell.style.bottom=`${Math.max(44,Math.round((window.innerHeight-(status?.top||window.innerHeight))+8))}px`;}
    updateCollapseLabel(shell);
  }
  function ensureLiveShell() {
    let shell = document.querySelector('#generation-live-shell');
    if (shell) return shell;
    shell = document.createElement('section');shell.id='generation-live-shell';shell.className='generation-live-shell compact glass';shell.style.setProperty('--live-visible-rows',MAX_VISIBLE_LIVE_ROWS);
    shell.innerHTML=`<header class="generation-live-head"><div class="generation-live-title"><span class="live-dot"></span><b>实时任务坞</b><button class="ghost" id="generation-live-collapse">收起</button></div><div class="generation-live-summary"><span>运行 <b id="generation-live-running">0</b></span><span>排队 <b id="generation-live-queued">0</b></span><span class="attention">需处理 <b id="generation-live-attention">0</b></span></div></header><div class="generation-live-dock" id="generation-live-dock"></div><section class="generation-live-detail"><div class="generation-live-detail-head"><div><small id="generation-live-priority">当前任务</small><b id="generation-live-title">任务现场</b></div><button class="ghost" id="generation-live-open">打开现场</button></div><div class="generation-live-meta"><span id="generation-live-account">执行通道</span><span id="generation-live-stage">准备任务</span></div><div class="generation-live-status" id="generation-live-status">正在准备</div><div class="generation-live-progress" id="generation-live-progress"><i></i></div><div class="generation-live-notice" id="generation-live-notice">任务状态会在这里实时更新。</div><div class="generation-live-actions"><button class="ghost" data-task-open-scene>打开原会话</button><button class="primary" data-task-resume>完成登录/验证，继续</button><button class="primary" data-task-monitor-unknown>已确认提交，继续监控</button><button class="ghost warning" data-task-resolve-failed>确认豆包已失败</button><button class="ghost warning" data-task-resolve-not-submitted>确认未提交，结束保护</button><button class="primary" data-doubao-result-retry>重新回传</button><button class="ghost warning" data-doubao-result-cancel>取消回传</button><button class="ghost" data-live-model-edit>修改结果</button><button class="ghost" data-live-model-pause>暂停</button><button class="primary" data-live-model-resume>继续</button><button class="ghost" data-live-model-retry>重试回传</button><button class="ghost warning" data-live-model-cancel>取消</button></div></section>`;
    document.body.appendChild(shell);
    shell.querySelector('[data-task-monitor-unknown]').textContent='校验当前会话并继续';
    shell.querySelector('#generation-live-collapse').onclick=()=>{const pageShell=document.querySelector('.shell');if(shell.classList.contains('rail-unavailable')){const tasksButton=[...document.querySelectorAll('[data-page]')].find(button=>button.dataset.page==='tasks');tasksButton?.click();return;}shell.dataset.userCollapsed='true';const panelToggle=document.querySelector('#right-panel-toggle');if(panelToggle&&!pageShell?.classList.contains('right-off'))panelToggle.click();else pageShell?.classList.add('right-off');syncLiveRailLayout(shell);};
    shell.querySelector('#generation-live-open').onclick=async()=>{const item=activeTask();if(!canOpenWindow(item))return;try{await api.doubao?.activateAccount(item.accountId)}catch(error){toast(String(error.message||error),true)}};
    syncLiveRailLayout(shell);return shell;
  }
  function applyLiveTask(shell,item) {
    if(!shell||!item)return;if(!isLiveDockTask(item)){liveTasks.delete(item.taskId);activeLiveTaskId='';renderLiveDock(shell);return;}activeLiveTaskId=item.taskId;shell.dataset.liveTaskId=item.taskId||'';shell.dataset.liveChannel=item.executionChannel||'';
    const stage=stageLabel(item),elapsed=elapsedLabel(item),checked=checkedLabel(item.lastCheckedAt),indeterminate=isIndeterminate(item);
    shell.querySelector('#generation-live-priority').textContent=needsLiveAttention(item)?'需要处理':runningStates.has(item.state)?'正在执行':item.state==='queued'?'等待队列':'任务详情';
    shell.querySelector('#generation-live-title').textContent=item.title||'任务';shell.querySelector('#generation-live-account').textContent=item.executionChannel==='doubao'?(item.accountName||item.accountId||'豆包账号'):(item.modelId||'模型网关');shell.querySelector('#generation-live-stage').textContent=stage;
    shell.querySelector('#generation-live-status').textContent=indeterminate?`${item.statusText||stage}${elapsed?` · 已运行 ${elapsed}`:''}${checked?` · 最近检查 ${checked}`:''}`:`${item.statusText||stage} · ${Math.round(Number(item.progress)||0)}%`;
    const progress=shell.querySelector('#generation-live-progress');progress.classList.toggle('indeterminate',indeterminate);progress.classList.toggle('warning',needsLiveAttention(item)||item.state==='awaiting_quota');progress.querySelector('i').style.width=indeterminate?'38%':`${Math.max(0,Math.min(100,Number(item.progress)||0))}%`;
    shell.querySelector('#generation-live-open').style.display=canOpenWindow(item)?'':'none';const notice=shell.querySelector('#generation-live-notice');notice.classList.toggle('warning',needsLiveAttention(item)||item.state==='awaiting_quota'||item.state==='downloading');
    notice.textContent=item.terminalFailureVerified?`${item.userAction||item.providerMessage||'平台已明确结束本次生成。'} 任务监控已停止。`:item.state==='awaiting_verification'?'豆包需要人工验证：打开原账号现场，完成后点击“继续”，系统会沿用原任务和原 conversation。':item.state==='awaiting_login'?'豆包登录已失效：打开原账号重新登录后点击“继续”，不会重新提交。':item.state==='submission_unknown'&&item.executionChannel==='doubao'?'提交证据不完整：账号保持锁定。请打开原会话核对，再明确选择继续监控或确认未提交；系统不会自动重提。':item.state==='submission_unknown'?modelUnknownNotice(item):item.state==='awaiting_quota'?'候选豆包账号额度暂不可用，任务会在额度刷新后重新调度。':item.executionChannel==='model-gateway'&&item.state==='paused'?`${item.userAction||'模型任务已暂停。'} 当前已入库 ${Number(item.recoveredResultCount||0)}/${Number(item.expectedResultCount||0)} 项，可修改地址、继续或仅重试回传。`:item.executionChannel==='doubao'&&item.state==='downloading'?'豆包结果已经生成；仅恢复原结果下载与素材回填，不会重新提交，原账号和会话保持绑定。':item.executionChannel==='model-gateway'&&item.state==='downloading'?`厂商已经生成成功；正在逐项回传 ${Number(item.recoveredResultCount||0)}/${Number(item.expectedResultCount||0)}，不会重新提交。`:item.executionChannel==='model-gateway'?'模型网关任务在独立任务池并行运行，不占用豆包队列。':terminalStates.has(item.state)?'任务已结束，记录可从任务坞历史或来源模块查看。':'豆包任务在独立账号窗口运行，可继续使用工作台其他模块。';
    const actions=shell.querySelector('.generation-live-actions'),openAction=actions.querySelector('[data-task-open-scene]'),resumeAction=actions.querySelector('[data-task-resume]'),monitorAction=actions.querySelector('[data-task-monitor-unknown]'),failedAction=actions.querySelector('[data-task-resolve-failed]'),resolveAction=actions.querySelector('[data-task-resolve-not-submitted]'),doubaoRetry=actions.querySelector('[data-doubao-result-retry]'),doubaoCancel=actions.querySelector('[data-doubao-result-cancel]'),modelEdit=actions.querySelector('[data-live-model-edit]'),modelPause=actions.querySelector('[data-live-model-pause]'),modelResume=actions.querySelector('[data-live-model-resume]'),modelRetry=actions.querySelector('[data-live-model-retry]'),modelCancel=actions.querySelector('[data-live-model-cancel]');const isDoubao=item.executionChannel==='doubao',isModel=item.executionChannel==='model-gateway'&&!terminalStates.has(item.state),canResume=isDoubao&&['awaiting_verification','awaiting_login'].includes(item.state),isUnknown=isDoubao&&item.state==='submission_unknown',doubaoResult=isDoubao&&(item.resultUrls||[]).length&&['downloading','verifying','paused','failed'].includes(item.state)&&(item.retryMode==='recover_result'||['result_download_failed','result_review_required','validating_result','manual_retry'].includes(item.recoveryState));actions.style.display=(canResume||isUnknown||isModel||doubaoResult)?'flex':'none';openAction.style.display=canOpenWindow(item)?'':'none';openAction.dataset.accountId=item.accountId||'';for(const button of [resumeAction,monitorAction,failedAction,resolveAction,doubaoRetry,doubaoCancel,modelEdit,modelPause,modelResume,modelRetry,modelCancel])button.dataset.taskId=item.taskId||'';resumeAction.style.display=canResume?'':'none';monitorAction.style.display=isUnknown?'':'none';failedAction.style.display=isUnknown?'':'none';resolveAction.style.display=isUnknown?'':'none';doubaoRetry.style.display=doubaoResult?'':'none';doubaoCancel.style.display=doubaoResult?'':'none';modelEdit.style.display=isModel?'':'none';modelPause.style.display=isModel&&item.state!=='paused'&&!['preparing','submitting'].includes(item.state)?'':'none';modelResume.style.display=isModel&&item.state==='paused'?'':'none';modelRetry.style.display=isModel&&((item.resultItems||[]).length||(item.resultUrls||[]).length||item.providerJobId||item.clientRequestId)?'':'none';modelCancel.style.display=isModel?'':'none';
    renderLiveDock(shell);
  }
  function renderLiveDock(shell=document.querySelector('#generation-live-shell')) {
    const dock=shell?.querySelector('#generation-live-dock');if(!dock)return;const counts=summaryCounts();shell.querySelector('#generation-live-running').textContent=counts.running;shell.querySelector('#generation-live-queued').textContent=counts.queued;shell.querySelector('#generation-live-attention').textContent=counts.attention;
    shell.classList.toggle('empty',counts.total===0);
    shell.classList.toggle('idle',counts.total===0);
    dock.innerHTML=sortedLiveTasks().map(item=>`<button class="live-task-chip ${item.taskId===activeLiveTaskId?'active':''} ${needsLiveAttention(item)?'attention':''}" data-live-task="${esc(item.taskId)}"><b>${esc(item.executionChannel==='model-gateway'?'模型':'豆包')}</b><span><strong>${esc(item.accountName||item.modelId||'执行通道')}</strong><small>${esc(item.title||'任务')}</small></span><em>${esc(isIndeterminate(item)?stageLabel(item):(stageLabels[item.state]||`${Math.round(Number(item.progress)||0)}%`))}</em></button>`).join('')||'<div class="generation-live-empty">暂无进行中的任务<br><span>新任务开始后会在这里实时显示。</span></div>';
    dock.querySelectorAll('[data-live-task]').forEach(button=>button.onclick=()=>{const item=liveTasks.get(button.dataset.liveTask);if(!item)return;activeLiveTaskId=item.taskId;applyLiveTask(shell,item)});updateCollapseLabel(shell);
  }
  function receiveLive(payload) {
    if(!payload?.taskId)return;const previous=liveTasks.get(payload.taskId)||{};const nextValue={...previous,...payload,receivedAt:previous.receivedAt||new Date().toISOString(),terminalAt:terminalStates.has(payload.state)?(previous.terminalAt||Date.now()):0};if(!isLiveDockTask(nextValue)){liveTasks.delete(payload.taskId);if(activeLiveTaskId===payload.taskId)activeLiveTaskId='';const shell=ensureLiveShell(),nextTask=sortedLiveTasks()[0];if(nextTask)applyLiveTask(shell,nextTask);else renderLiveDock(shell);syncLiveRailLayout(shell);return;}liveTasks.set(payload.taskId,nextValue);trimLiveTasks();
    const shell=ensureLiveShell(),current=activeTask(),incoming=liveTasks.get(payload.taskId);if(!current||attentionRank(incoming)<attentionRank(current))activeLiveTaskId=payload.taskId;if(needsLiveAttention(incoming)&&shell.dataset.userCollapsed!=='true')shell.classList.remove('collapsed');applyLiveTask(shell,activeTask()||incoming);syncLiveRailLayout(shell);
  }
  async function hydrateLiveTasks() {
    try {
      const data=await api.workbench?.bootstrap?.();
      const restorable=new Set([...runningStates,'queued','awaiting_quota','awaiting_verification','awaiting_login','submission_unknown','paused']);
      const tasks=(data?.tasks||[]).filter(item=>isLiveDockTask(item)&& (restorable.has(item.state)||isRecoverableFailure(item))).slice(0,24);
      for(const task of tasks)receiveLive({...task,taskId:task.id,restoredFromTaskCenter:true});
      if(!tasks.length)renderLiveDock(ensureLiveShell());
    } catch(error) { console.warn('restore live task dock failed',error); }
  }
  api.generation.onLiveView?.(receiveLive);
  api.generation.onLiveStatus?.(payload=>{if(!payload?.taskId)return;window.dispatchEvent(new CustomEvent('lingframe:generation-status',{detail:payload}));receiveLive(payload)});
  window.addEventListener('resize',()=>syncLiveRailLayout());new MutationObserver(()=>{const shell=document.querySelector('#generation-live-shell');if(shell)queueMicrotask(()=>syncLiveRailLayout(shell))}).observe(document.querySelector('#root')||document.body,{childList:true,subtree:true});setInterval(()=>{trimLiveTasks();const shell=document.querySelector('#generation-live-shell'),item=activeTask();if(shell&&item)applyLiveTask(shell,item)},30000);
  hydrateLiveTasks();
  loadProviders();
})();
