const {contextBridge, ipcRenderer} = require('electron');
contextBridge.exposeInMainWorld('lingframe', {
  window: {minimize:()=>ipcRenderer.invoke('window:minimize'), toggleMaximize:()=>ipcRenderer.invoke('window:toggle-maximize'), close:()=>ipcRenderer.invoke('window:close'), isMaximized:()=>ipcRenderer.invoke('window:is-maximized')},
  app: {diagnostics:()=>ipcRenderer.invoke('app:diagnostics'), openExternal:(url)=>ipcRenderer.invoke('app:open-external',url)},
  updates: {status:()=>ipcRenderer.invoke('app:update-status'), check:()=>ipcRenderer.invoke('app:update-check'), download:()=>ipcRenderer.invoke('app:update-download'), install:()=>ipcRenderer.invoke('app:update-install'), onStatus:(handler)=>ipcRenderer.on('app:update-status',(_,data)=>handler(data))},
  connection: {status:()=>ipcRenderer.invoke('connection:status'), refresh:()=>ipcRenderer.invoke('connection:refresh'), verifyAdmin:(input)=>ipcRenderer.invoke('connection:admin-verify',input), adminStatus:(sessionId)=>ipcRenderer.invoke('connection:admin-status',sessionId), applyAdmin:(sessionId,input)=>ipcRenderer.invoke('connection:admin-apply',sessionId,input)},
  identity: {status:()=>ipcRenderer.invoke('identity:status')},
  auth: {status:()=>ipcRenderer.invoke('auth:status'), bootstrap:()=>ipcRenderer.invoke('auth:desktop-bootstrap'), login:(input)=>ipcRenderer.invoke('auth:login',input), register:(input)=>ipcRenderer.invoke('auth:register',input), selectTenant:(tenantId)=>ipcRenderer.invoke('auth:select-tenant',tenantId), refresh:()=>ipcRenderer.invoke('auth:refresh'), logout:()=>ipcRenderer.invoke('auth:logout'), onChanged:(handler)=>ipcRenderer.on('auth:changed',(_,data)=>handler(data))},
  agent: {status:()=>ipcRenderer.invoke('agent:status'), configure:(config)=>ipcRenderer.invoke('agent:configure',config), openAccount:(account)=>ipcRenderer.invoke('agent:open-account',account), detectAccount:(account)=>ipcRenderer.invoke('agent:detect-account',account)},
  workbench: {bootstrap:()=>ipcRenderer.invoke('workbench:bootstrap')},
  credits: {wallet:()=>ipcRenderer.invoke('credits:wallet'), packages:()=>ipcRenderer.invoke('credits:packages'), orders:()=>ipcRenderer.invoke('credits:orders'), ledger:(limit,cursor)=>ipcRenderer.invoke('credits:ledger',limit,cursor), createOrder:(input)=>ipcRenderer.invoke('credits:create-order',input), cancelOrder:(orderId)=>ipcRenderer.invoke('credits:cancel-order',orderId)},
  models: {bootstrap:()=>ipcRenderer.invoke('models:bootstrap'), catalog:()=>ipcRenderer.invoke('models:catalog'), executionCatalog:()=>ipcRenderer.invoke('models:execution-catalog'), createProvider:(input)=>ipcRenderer.invoke('models:create-provider',input), updateProvider:(id,input)=>ipcRenderer.invoke('models:update-provider',id,input), deleteProvider:(id)=>ipcRenderer.invoke('models:delete-provider',id), testProvider:(id)=>ipcRenderer.invoke('models:test-provider',id), discover:(id)=>ipcRenderer.invoke('models:discover',id), addModel:(id,input)=>ipcRenderer.invoke('models:add-model',id,input), updateModel:(id,modelId,input)=>ipcRenderer.invoke('models:update-model',id,modelId,input), deleteModel:(id,modelId)=>ipcRenderer.invoke('models:delete-model',id,modelId)},
  projects: {create:(input)=>ipcRenderer.invoke('projects:create',input), update:(id,input)=>ipcRenderer.invoke('projects:update',id,input), setCurrent:(id)=>ipcRenderer.invoke('projects:set-current',id), delete:(id)=>ipcRenderer.invoke('projects:delete',id), restore:(id)=>ipcRenderer.invoke('projects:restore',id)},
  assets: {list:(filters)=>ipcRenderer.invoke('assets:list',filters), pickImport:(input)=>ipcRenderer.invoke('assets:pick-import',input), import:(input)=>ipcRenderer.invoke('assets:import',input), createText:(input)=>ipcRenderer.invoke('assets:create-text',input), copy:(input)=>ipcRenderer.invoke('assets:copy',input), preview:(id)=>ipcRenderer.invoke('assets:preview',id), update:(id,input)=>ipcRenderer.invoke('assets:update',id,input), delete:(id)=>ipcRenderer.invoke('assets:delete',id), restore:(id)=>ipcRenderer.invoke('assets:restore',id), open:(id)=>ipcRenderer.invoke('assets:open',id), showInFolder:(id)=>ipcRenderer.invoke('assets:show-in-folder',id), readText:(id)=>ipcRenderer.invoke('assets:read-text',id)},
  text: {create:(input)=>ipcRenderer.invoke('text:create',input), update:(id,input)=>ipcRenderer.invoke('text:update',id,input), delete:(id)=>ipcRenderer.invoke('text:delete',id), restore:(id)=>ipcRenderer.invoke('text:restore',id), restoreVersion:(id,versionId)=>ipcRenderer.invoke('text:restore-version',id,versionId), deleteVersion:(id,versionId)=>ipcRenderer.invoke('text:delete-version',id,versionId)},
  tasks: {create:(input)=>ipcRenderer.invoke('tasks:create',input), report:(id,input)=>ipcRenderer.invoke('tasks:report',id,input), complete:(id,input)=>ipcRenderer.invoke('tasks:complete',id,input), updateResultUrl:(id,url)=>ipcRenderer.invoke('tasks:update-result-url',id,url), cancel:(id)=>ipcRenderer.invoke('tasks:cancel',id), retry:(id,input)=>ipcRenderer.invoke('tasks:retry',id,input), archive:(id,archived=true)=>ipcRenderer.invoke('tasks:archive',id,archived), delete:(id)=>ipcRenderer.invoke('tasks:delete',id), restore:(id)=>ipcRenderer.invoke('tasks:restore',id)}
  ,generation: {create:(input)=>ipcRenderer.invoke('generation:create',input), run:(id)=>ipcRenderer.invoke('generation:run',id), resume:(id)=>ipcRenderer.invoke('generation:resume',id), monitor:(id)=>ipcRenderer.invoke('generation:monitor',id), resolveSubmissionUnknown:(id,resolution)=>ipcRenderer.invoke('generation:resolve-submission-unknown',id,resolution), pauseModel:(id)=>ipcRenderer.invoke('generation:model-pause',id), resumeModel:(id)=>ipcRenderer.invoke('generation:model-resume',id), retryModelResult:(id)=>ipcRenderer.invoke('generation:model-retry-result',id), updateModelResult:(id,input)=>ipcRenderer.invoke('generation:model-update-result',id,input), retryDoubaoResult:(id)=>ipcRenderer.invoke('generation:doubao-retry-result',id), cancel:(id)=>ipcRenderer.invoke('generation:cancel',id), onLiveView:(handler)=>ipcRenderer.on('generation:live-view',(_,data)=>handler(data)), onLiveStatus:(handler)=>ipcRenderer.on('generation:live-status',(_,data)=>handler(data))}
  ,doubao: {open:(account, options)=>ipcRenderer.invoke('doubao:open',account,options), detect:(account)=>ipcRenderer.invoke('doubao:detect',account), close:(account)=>ipcRenderer.invoke('doubao:close',account), popout:(account)=>ipcRenderer.invoke('doubao:popout',account), activateAccount:(accountId)=>ipcRenderer.invoke('doubao:activate-account',accountId), hideAccount:(accountId)=>ipcRenderer.invoke('doubao:hide-account',accountId), setBounds:(bounds)=>ipcRenderer.invoke('doubao:set-bounds',bounds), setPageActive:(active)=>ipcRenderer.invoke('doubao:set-page-active',active), status:(accountId)=>ipcRenderer.invoke('doubao:status',accountId), onStatus:(handler)=>ipcRenderer.on('doubao:embedded-status',(_,data)=>handler(data))}
  ,doubaoAccounts: {bootstrap:(input)=>ipcRenderer.invoke('doubao-accounts:bootstrap',input), list:()=>ipcRenderer.invoke('doubao-accounts:list'), upsert:(input)=>ipcRenderer.invoke('doubao-accounts:upsert',input), remove:(accountId)=>ipcRenderer.invoke('doubao-accounts:remove',accountId), discoverLocal:()=>ipcRenderer.invoke('doubao-accounts:discover-local'), importLocal:(candidateRef)=>ipcRenderer.invoke('doubao-accounts:import-local',candidateRef)}
});
